# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
include:
  - component: $CI_SERVER_FQDN/templates/components/workflow/default@0.4.0
  - component: $CI_SERVER_FQDN/templates/components/publish/live@0.6.0
  - component: $CI_SERVER_FQDN/templates/components/renovate/renovate@0.8.0
  - component: $CI_SERVER_FQDN/templates/components/docker/amd64@1.6.0
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - when: always
  - component: $CI_SERVER_FQDN/templates/components/docker/arm64@1.6.0
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - when: always
  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.6.0
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - when: always
    inputs:
      needs:
        - docker:amd64
        - docker:arm64
      args: >-
        --cache-from=type=registry,ref=$DOCKER_IMAGE_CACHE_PATH:amd64
        --cache-from=type=registry,ref=$DOCKER_IMAGE_CACHE_PATH:arm64
      tag: $DOCKER_IMAGE_PATH:latest
  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.6.0
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      name: release
      tag: $DOCKER_IMAGE_PATH:$CI_COMMIT_TAG

keepalived:
  stage: deploy
  trigger:
    forward:
      yaml_variables: false
      pipeline_variables: false
    project: docker/keepalived
