# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
include:
  - component: $CI_SERVER_FQDN/templates/components/workflow/default@0.1.1
  - component: $CI_SERVER_FQDN/templates/components/publish/live@0.3.0

  - component: $CI_SERVER_FQDN/templates/components/docker/amd64@1.1.0
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      - if: $CI_PIPELINE_SOURCE == "schedule"
      - if: $CI_PIPELINE_SOURCE == "push"
    inputs:
      healthcheck-uuid: 591ad74e-5888-492c-8d4e-c76eeb594ca3

  - component: $CI_SERVER_FQDN/templates/components/docker/arm64@1.1.0
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      - if: $CI_PIPELINE_SOURCE == "schedule"
      - if: $CI_PIPELINE_SOURCE == "push"
    inputs:
      healthcheck-uuid: 568305a7-b580-49df-94e2-992be44e1604

  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.1.0
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      - if: $CI_PIPELINE_SOURCE == "schedule"
      - if: $CI_PIPELINE_SOURCE == "push"
    inputs:
      needs:
        - docker:amd64
        - docker:arm64
      args: >-
        --cache-from=type=registry,ref=$DOCKER_IMAGE_CACHE_PATH:amd64
        --cache-from=type=registry,ref=$DOCKER_IMAGE_CACHE_PATH:arm64
      tag: $DOCKER_IMAGE_PATH:latest
      healthcheck-uuid: 05d4a642-89c0-4431-8d87-2e9aceb2d001

  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.1.0
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      name: release
      tag: $DOCKER_IMAGE_PATH:$CI_COMMIT_TAG
