# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
include:
  - component: $CI_SERVER_FQDN/templates/components/workflow/default@0.1.2
  - component: $CI_SERVER_FQDN/templates/components/publish/live@0.5.1

  - component: $CI_SERVER_FQDN/templates/components/docker/amd64@1.3.4
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - when: always
    inputs:
      healthcheck-uuid: baae4307-b60d-4117-8bfa-d93659ef41ad

  - component: $CI_SERVER_FQDN/templates/components/docker/arm64@1.3.4
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - when: always
    inputs:
      healthcheck-uuid: 55cd2335-ade9-4dde-8f0d-bca421b537f9

  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.3.4
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - when: always
    inputs:
      needs:
        - docker:amd64
        - docker:arm64
      args: >-
        --cache-from=type=registry,ref=$DOCKER_IMAGE_CACHE_PATH:amd64
        --cache-from=type=registry,ref=$DOCKER_IMAGE_CACHE_PATH:arm64
      tag: $DOCKER_IMAGE_PATH:latest
      healthcheck-uuid: c2e4abd7-63b3-40e6-bc34-c51f7ce032db

  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.3.4
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      name: release
      tag: $DOCKER_IMAGE_PATH:$CI_COMMIT_TAG

keepalived:
  stage: deploy
  trigger:
    forward:
      yaml_variables: false
      pipeline_variables: false
    project: docker/keepalived
