#!/usr/bin/env bash
# shellcheck shell=bash

wget -L -O /tmp/noarch.tar.xz https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz
tar -C / -Jxpf /tmp/noarch.tar.xz

ARCH="${TARGETARCH}"
case "${TARGETARCH}" in
    amd64)
        ARCH=x86_64
    ;;
    arm64)
        ARCH=aarch64
    ;;
esac

wget -L -O /tmp/arch.tar.xz https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-${ARCH}.tar.xz
tar -C / -Jxpf /tmp/arch.tar.xz

wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [arch=${TARGETARCH} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
apt-get update
apt-get install -y nomad
