#!/usr/bin/env bash
# shellcheck shell=bash

wget -L -O /tmp/noarch.tar.xz https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz
tar -C / -Jxpf /tmp/noarch.tar.xz

ARCH="${TARGETARCH}"
case "${TARGETARCH}" in
    amd64)
        ARCH=x86_64
    ;;
    arm64)
        ARCH=aarch64
    ;;
esac

wget -L -O /tmp/arch.tar.xz https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-${ARCH}.tar.xz
tar -C / -Jxpf /tmp/arch.tar.xz
