---
name: docker-main

on:
  push:
    branches:
      - main
      - master

env:
  PLATFORM: linux/amd64,linux/arm64,linux/arm/v7
  DOCKERHUB_REPO: "${{ vars.DOCKERHUB_ORG }}/ubuntu-service"
  BUILD_DATE: "${{ github.event.repository.updated_at }}"
  CI_PROJECT_NAME: "${{ github.repository }}"
  VCS_REF_NAME: "${{ github.ref_name }}"
  VCS_REF_SHA: "${{ github.sha }}"


jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME || '' }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD || '' }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha
          platforms: ${{ env.PLATFORM }}
          tags: ${{ env.DOCKERHUB_REPO }}:main
          build-args: |
            VERSION=main

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME || '' }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD || '' }}"
          repository: ${{ env.DOCKERHUB_REPO }}
          readme-filepath: README.md
